name: CI - FastAPI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name:  Checkout do c贸digo
        uses: actions/checkout@v4

      - name:  Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: И Criar ambiente virtual
        run: |
          python -m venv .venv
          source .venv/bin/activate

      - name: 猬锔 Atualizar pip
        run: |
          source .venv/bin/activate
          pip install --upgrade pip

      - name:  Instalar depend锚ncias
        run: |
          source .venv/bin/activate
          pip install fastapi uvicorn sqlalchemy pydantic python-dotenv
          pip install pytest pytest-cov httpx

      - name: И Rodar testes
        run: |
          source .venv/bin/activate
          pytest --cov=app --cov-report=term-missing

      - name:  Gerar relat贸rio de cobertura
        run: |
          source .venv/bin/activate
          pytest --cov=app --cov-report=xml

      - name:  Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

      - name:  Enviar relat贸rio por e-mail
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "CI - Resultado dos testes"
          body: |
            Pipeline executada com status: ${{ job.status }}

            Reposit贸rio: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}

            O relat贸rio de cobertura est谩 anexado.
          to: ${{ secrets.EMAIL_TO }}
          from: GitHub Actions
          attachments: coverage.xml