name: CI - FastAPI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout do cÃ³digo
        uses: actions/checkout@v4

      - name: ğŸ Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: ğŸ§ª Criar ambiente virtual
        run: |
          python -m venv .venv
          source .venv/bin/activate

      - name: â¬†ï¸ Atualizar pip
        run: |
          source .venv/bin/activate
          pip install --upgrade pip

      - name: ğŸ“¦ Instalar dependÃªncias
        run: |
          source .venv/bin/activate
          pip install fastapi uvicorn sqlalchemy pydantic python-dotenv
          pip install pytest pytest-cov httpx

      - name: ğŸ§ª Rodar testes
        run: |
          source .venv/bin/activate
          pytest --cov=app --cov-report=term-missing

      - name: ğŸ“Š Gerar relatÃ³rio de cobertura
        run: |
          source .venv/bin/activate
          pytest --cov=app --cov-report=xml

      - name: ğŸ“ Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml